version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
      python: 3.7
    commands:
      - pip3 install chalice==1.12.0
      - wget https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip
      - unzip terraform_0.12.24_linux_amd64.zip
      - mv terraform /usr/local/bin/terraform
      - docker --version
      - python --version
      - chalice --version
      - terraform --version
  build:
    commands:
      # restore state
      - aws s3 sync --delete s3://${TERRAFORM_BACKEND_BUCKET}/admin_api/ admin_api/.chalice/deployed/
      - python deploy.py
      # save state
      - aws s3 sync --delete admin_api/.chalice/deployed/ s3://${TERRAFORM_BACKEND_BUCKET}/admin_api/
